# Build and Test Workflow for DungineX

name: Multi-Platform Build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    # There is an issue with windows-latest to compile SDL3.
    # See: https://github.com/libsdl-org/SDL/issues/11487#issuecomment-2854148376
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2025, ubuntu-latest]
        generator: ["Visual Studio 17 2022", Ninja]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-2025
            c_compiler: cl
            cxx_compiler: cl
          - os: ubuntu-latest
            generator: Ninja
            c_compiler: gcc
            cxx_compiler: g++
          - os: ubuntu-latest
            generator: Ninja
            c_compiler: clang
            cxx_compiler: clang++
        exclude:
          - os: windows-2025
            generator: Ninja
          - os: windows-2025
            c_compiler: gcc
          - os: windows-2025
            c_compiler: clang
          - os: ubuntu-latest
            generator: "Visual Studio 17 2022"
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Ninja
      if: matrix.generator == 'Ninja'
      uses: ashutoshvarma/setup-ninja@master

    - name: CMake ${{ matrix.build_type }} Windows
      if: matrix.os == 'windows-2025'
      run: >
        cmake -S . -B build -G "${{ matrix.generator }}"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DDGEX_BUILD_DEMO=OFF
        -DDGEX_USE_SHARED=OFF

    - name: CMake ${{ matrix.build_type }} Linux
      if: matrix.os == 'ubuntu-latest'
      run: >
        cmake -S . -B build -G "${{ matrix.generator }}"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}
        -DDGEX_BUILD_DEMO=OFF
        -DDGEX_USE_SHARED=OFF
        -DSDL_UNIX_CONSOLE_BUILD=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel

    - name: Test
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }}
