# Build and Test Workflow for DungineX

name: Linux Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        generator: [ Ninja ]
        cc: [ gcc, clang ]
        build_type: [ Release ]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master

    - name: CMake ${{ matrix.build_type }} Linux
      run: >
        cmake -S . -B build -G "${{ matrix.generator }}"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_C_COMPILER=${{ matrix.cc }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
        -DDGEX_BUILD_DEMO=OFF
        -DDGEX_USE_SHARED=OFF
        -DSDL_UNIX_CONSOLE_BUILD=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel

    - name: Test
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }}
