# Build and Test Workflow for DungineX

name: Windows Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    # There is an issue with windows-latest to compile SDL3.
    # See: https://github.com/libsdl-org/SDL/issues/11487#issuecomment-2854148376
    runs-on: windows-2025
    strategy:
      fail-fast: true
      matrix:
        generator: [ "Visual Studio 17 2022" ]
        build_type: [ Release ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: CMake ${{ matrix.build_type }} Windows
      run: >
        cmake -S . -B build -G "${{ matrix.generator }}"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DDGEX_BUILD_DEMO=OFF
        -DDGEX_USE_SHARED=OFF

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel

    - name: Test
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }}
